### ISSUE TITLE
[FEATURE] 노래관리하는 기능 추가

### ISSUE THREAD

**Issue by donsonioc2010** [nerd-team-1/favorite-18-server#18]
# 🤖 기능 개요
노래를 관리하는 부분에 대하여 기능을 추가합니다.

### ✅ Implement TODO
- 노래
    - [x] Song관련 Entity추가
    - [x] 검색어를 바탕으로 노래를 조회하는 기능
    - [x] 노래의 세부 페이지를 조회하는 기능
    - [ ] 크롤링, 기존에 이미 등록된 번호 가져올 수 있는 방안 찾기.

### 📚 Remarks
흑흑....

**Comment by JakePark929** [comment]
기능 몇 개 나눠서 같이 보셔도 되는데 이걸 다요..?

**Comment by donsonioc2010** [comment]
그러네요 생각해보니 이 티켓에는 노래만 일단 있어야 겠네요 ㅋㅋㅋㅋ
